In [7]:
import numpy as np

# 1. Array de 10 elementos, todos com valor 5
array = np.full(10, 5)
print("Array de 10 elementos = 5:", array)

Array de 10 elementos = 5: [5 5 5 5 5 5 5 5 5 5]


In [13]:
# 2. Array de 10 elementos, de 0 a 9
array = np.arange(10)
print("Array de 0 a 9:", array)

Array de 0 a 9: [0 1 2 3 4 5 6 7 8 9]


In [9]:

# 3. Matriz 3x3 com valores aleatórios entre 0 e 1
matriz = np.random.rand(3, 3)
print("Matriz 3x3 aleatória (0 a 1):\n", matriz)

Matriz 3x3 aleatória (0 a 1):
 [[0.20057345 0.25642964 0.92326015]
 [0.15570766 0.95274206 0.99324902]
 [0.61268455 0.87007173 0.66735378]]


In [11]:
# 4. Array de 5 elementos alternando entre True e False
array = np.array([True, False] * 3)[:5]
print("Array alternando True/False:", array)

Array alternando True/False: [ True False  True False  True]
